[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Production backend URL (Fly.io - NO COLD START!)
  NEXT_PUBLIC_API_URL = "https://gedaechtnisboost-backend.fly.dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"
